import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from '@/redux/services/providers'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Providers>
        <body className={inter.className}>
          <nav className='flex gap-6 p-4 text-blue-400 text-2xl'>
            <Link href='/'>Home</Link>
            <Link href='./mall'>Mall</Link>
            <Link href='./cart'>Cart</Link>
          </nav>
          {children}
        </body>
      </Providers>
    </html>
  )
}
